name: googleSheetMenu_master

on:
  repository_dispatch:
    types: [googleSheetMenu]

jobs:
  production_deploy:
    runs-on: macos-latest
    steps:
      - name: Setup Timezone
        run: |
          sudo systemsetup -settimezone Asia/Tokyo
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: restore node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-16-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-16-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Copy data.json to master
        run: |
          curl -o data/daily_positive_detail.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/daily_positive_detail.json
          curl -o data/data.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/data.json
          curl -o data/patient_municipalities.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/patient_municipalities.json
          curl -o data/health_burden.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/health_burden.json
          curl -o data/positive_rate.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/positive_rate.json
          curl -o data/positive_status.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/positive_status.json
          curl -o data/news.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/news.json
          curl -o data/alert.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/alert.json
          curl -o data/urls.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/urls.json
          curl -o data/self_disclosures.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/self_disclosures.json
          curl -o data/main_summary.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/main_summary.json
          curl -o data/confirmed_case_area.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/confirmed_case_area.json
          curl -o data/confirmed_case_age.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/master/data/confirmed_case_age.json
      - name: yarn run generate:deploy for generate OGP
        run: |
          yarn run generate:deploy --fail-on-page-error
        env:
          TZ: Asia/Tokyo
      - name: install selenium
        run: pip3 install selenium
      - name: generate ogp with weekly-map
        run: |
          python3 -m http.server --directory ./dist 8000 &
          python3 ./ui-test/ogp_screenshot.py
          node ./ui-test/ogp_composite_weekly_map.js
      - name: Commit OGP & JSON files to master
        run: |
          cp -f static/ogp.png dist/ogp.png
          cp -rp ogp dist/
          cp -rp ogp static/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status | grep modified && git add data static && git commit -v -m "[Bot] update data/*.json and static at $(date +'%Y-%m-%dT%H:%M:%S%z')"
      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      - name: production deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: production
      - name: sitemap ping to google
        run: |
          curl "https://www.google.com/ping?sitemap=https://iwate.stopcovid19.jp/sitemap.xml"
