name: on_pr_from_renovate_rspec

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  rspec:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Timezone
        run: |
          sudo timedatectl set-timezone Asia/Tokyo
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
      - name: restore node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-16-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-16-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: yarn run generate:deploy for rspec
        run: |
          yarn run generate:deploy --fail-on-page-error
        env:
          TZ: Asia/Tokyo
      - name: run localhost:3000
        run: |
          yarn run start &
      - name: rspec
        run: |
          bundle exec rspec spec/feature/index/shared/index_h1h2_spec.rb
          bundle exec rspec spec/feature/check_broken_links_spec.rb
      - name: upload rspec screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: rspec-screenshots
          path: spec/screenshot
          retention-days: 3
